#pragma checksum "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "45a29c37a4ef5a5c50fa6ec643ea8994411c6ab3"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(ClassExampleRazorPages.Pages.Pages_Index), @"mvc.1.0.razor-page", @"/Pages/Index.cshtml")]
namespace ClassExampleRazorPages.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\_ViewImports.cshtml"
using ClassExampleRazorPages;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"45a29c37a4ef5a5c50fa6ec643ea8994411c6ab3", @"/Pages/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"44e32a6fefc93c3a6feb0c3a2cb0788a55f62d52", @"/Pages/_ViewImports.cshtml")]
    public class Pages_Index : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
  
    ViewData["Title"] = "Home page";
    var Username = "TheUserNameOnTHePage";

#line default
#line hidden
#nullable disable
            WriteLiteral("    <p>Username the first time: ");
#nullable restore
#line 6 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
                           Write(Username);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n");
#nullable restore
#line 7 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"

    string[] people = { "Alex", "Peter", "Phil" };

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<div>\r\n    3 &lt; 5\r\n    &amp;\r\n</div>\r\n\r\n");
#nullable restore
#line 16 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
  
    Username = "ADifferentUsername";

#line default
#line hidden
#nullable disable
            WriteLiteral("<div class=\"text-center\">\r\n    <h1 class=\"display-4\">Hello there!</h1>\r\n    <p>The current time is ");
#nullable restore
#line 21 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
                      Write(DateTime.Now);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n    <p>amillerman01");
            WriteLiteral("@stclaircollege.ca</p>\r\n    <p>");
#nullable restore
#line 23 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
  Write(Username);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n    <p>");
#nullable restore
#line 24 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
  Write(Model.Username);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n    <p>");
#nullable restore
#line 25 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
  Write(DateTime.IsLeapYear(2020));

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n    <p>This time last week: ");
#nullable restore
#line 26 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
                        Write(DateTime.Now - TimeSpan.FromDays(7));

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n    <p>");
#nullable restore
#line 27 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
   Write("<span>A string in c#</span>");

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n\r\n\r\n    <div>\r\n");
#nullable restore
#line 31 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
         for (var i = 0; i < people.Length; i++)
        {
            var person = people[i];
            

#line default
#line hidden
#nullable disable
            WriteLiteral("Name: ");
#nullable restore
#line 34 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
                   Write(person);

#line default
#line hidden
#nullable disable
#nullable restore
#line 34 "G:\My Stuff\Documents\Teaching LOCAL\WEB 315\WEB315W22ClassExamples\ClassExampleRazorPages\Pages\Index.cshtml"
                                      
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("    </div>\r\n</div>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IndexModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<IndexModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<IndexModel>)PageContext?.ViewData;
        public IndexModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
